courtrun_legal_couriers/courtrun_legal_couriers/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('main.urls', namespace="main")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

    

courtrun_legal_couriers/main/urls.py
from django.urls import path
from . import views
from django.views.static import serve
from django.conf import settings

app_name = "main"

urlpatterns = [
	
	path('', views.home, name="home"),
    path('selection/', views.selection, name="selection"), 
	path('route/', views.route, name="route"),
    path('route-serve/', views.route_serve, name="route_serve"),
    path('route-file/', views.route_file, name="route_file"),
    path('route-summon/', views.route_summon, name="route_summon"),
    path('route-notice/', views.route_notice, name="route_notice"),
    path('route-correspondence/', views.route_correspondence, name="route_correspondence"),
	path('order-details', views.map, name="map"),
    path('serve-order-details', views.map_serve, name="map_serve"),
    path('file-order-details', views.map_file, name="map_file"),
    path('summon-order-details', views.map_summon, name="map_summon"),
    path('notice-order-details', views.map_notice, name="map_notice"),
    path('correspondence-order-details', views.map_correspondence, name="map_correspondence"),
    path('pricing/', views.pricing, name="pricing"),
	path('page-not-found/', views.page_not_found, name="page_not_found"), 
	path('popia/', views.popia, name="popia"),    
	path('faq/', views.faq, name="faq"),  
    path('contact/', views.contact, name="contact"),      
    path('confirmation/', views.confirmation, name="confirmation"),
    path('privacy-policy/', views.privacy_policy, name="privacy_policy"),
	path('terms-and-conditions', views.terms_and_conditions, name="terms_and_conditions"),       
    path('googlee7ff021fb9cd9b73.html', serve, {'document_root': settings.STATIC_ROOT}),
	]

courtrun_legal_couriers/main/views.py
from django.shortcuts import render
from django.conf import settings
from django.http import HttpResponseRedirect
from .forms import *
from .mixins import Directions
from django.core.mail import send_mail
from geopy.geocoders import GoogleV3
import uuid

geolocator = GoogleV3(api_key=settings.GOOGLE_API_KEY)


def home(request):
	return render(request, 'main/home.html')


def selection(request):
	return render(request, 'main/selection.html')


def route_serve(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route-serve.html', context)


def route_notice(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route-notice.html', context)


def route_correspondence(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route-correspondence.html', context)


def route_file(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY}
	return render(request, 'main/route-file.html', context)


def route(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY,}
	return render(request, 'main/route.html', context)


def route_summon(request):
	context = {"google_api_key": settings.GOOGLE_API_KEY,}
	return render(request, 'main/route-summon.html', context)


def map(request):

	lat_1 = request.GET.get("lat_1", None)
	long_1 = request.GET.get("long_1", None)
	lat_2 = request.GET.get("lat_2", None)
	long_2 = request.GET.get("long_2", None)
	lat_3 = request.GET.get("lat_3", None)
	long_3 = request.GET.get("long_3", None)
	lat_4 = request.GET.get("lat_4", None)
	long_4 = request.GET.get("long_4", None)
	lat_5 = request.GET.get("lat_5", None)
	long_5 = request.GET.get("long_5", None)
	lat_6 = request.GET.get("lat_6", None)
	long_6 = request.GET.get("long_6", None)
	lat_7 = request.GET.get("lat_7", None)
	long_7 = request.GET.get("long_7", None)
	lat_8 = request.GET.get("lat_8", None)
	long_8 = request.GET.get("long_8", None)


	lat_long_pairs = [
    (lat_1, long_1),
    (lat_2, long_2),
    (lat_3, long_3),
    (lat_4, long_4),
    (lat_5, long_5),
    (lat_6, long_6),
    (lat_7, long_7),
    (lat_8, long_8)
	]

	name_addresses = coordinate_converter(*lat_long_pairs)

	if lat_1 and lat_2:
		directions = Directions(
			lat_1= lat_1,
			long_1=long_1,
			lat_2 = lat_2,
			long_2=long_2,
			lat_3= lat_3,
			long_3=long_3,
			lat_4= lat_4,
			long_4=long_4,
			lat_5=lat_5,
			long_5=long_5,
			lat_6 = lat_6,
			long_6=long_6,
			lat_7= lat_7,
			long_7=long_7,
			long_8=long_8,
			lat_8=lat_8,
			)
		
	stops = directions["stops"]
	stop_number = []
	i = 0
	while i < stops:
		stop_number.append(i+1)
		i+=1

			
	stop_google_id = ["id-google-address-3", "id-google-address-4", "id-google-address-5", "id-google-address-6", "id-google-address-7", "id-google-address-8"]
	stop_name = ["stop1_address", "stop2_address", "stop3_address", "stop4_address", "stop5_address", "stop6_address"]
	stop_spec = ["stop1_spec", "stop2_spec", "stop3_spec", "stop4_spec", "stop5_spec", "stop6_spec"]
	stop_notes = ["stop1_notes", "stop2_notes", "stop3_notes", "stop4_notes", "stop5_notes", "stop6_notes"]
	stop_value = [name_addresses[2], name_addresses[3], name_addresses[4], name_addresses[5], name_addresses[6]]
	j = 0

	while j < stops:
		del stop_google_id[stops:]
		del stop_name[stops:]
		del stop_spec[stops:]
		del stop_value[stops:]
		del stop_notes[stops:]
		j+=1


	stop_info = zip(stop_number, stop_google_id, stop_name, stop_spec, stop_notes, stop_value)

	submitted = False
	if request.method == "POST":
		form = CollectionDropoffOrderForm(request.POST)

		if form.is_valid():
			form.save()
			orderId = form.cleaned_data.get('order_id')
			name = form.cleaned_data['name']
			email = form.cleaned_data['email']
			pickup_address = form.cleaned_data['pickup_address']
			pickup_spec = form.cleaned_data['pickup_spec']
			pickup_notes = form.cleaned_data['pickup_notes']
			stop1_address = form.cleaned_data['stop1_address']
			stop1_spec = form.cleaned_data.get('stop1_spec')
			stop1_notes = form.cleaned_data.get('stop1_notes')
			stop2_address = form.cleaned_data.get('stop2_address')
			stop2_spec = form.cleaned_data.get('stop2_spec')
			stop2_notes = form.cleaned_data.get('stop2_notes')
			stop3_address = form.cleaned_data.get('stop3_address')
			stop3_spec = form.cleaned_data.get('stop3_spec')
			stop3_notes = form.cleaned_data.get('stop3_notes')
			stop4_address = form.cleaned_data.get('stop4_address')
			stop4_spec = form.cleaned_data.get('stop4_spec')
			stop4_notes = form.cleaned_data.get('stop4_notes')
			stop5_address = form.cleaned_data.get('stop5_address')
			stop5_spec = form.cleaned_data.get('stop5_spec')
			stop5_notes = form.cleaned_data.get('stop5_notes')
			stop6_address = form.cleaned_data.get('stop6_address')
			stop6_spec = form.cleaned_data.get('stop6_spec')
			stop6_notes = form.cleaned_data.get('stop6_notes')
			dropoff_address = form.cleaned_data['dropoff_address']
			dropoff_spec = form.cleaned_data['dropoff_spec']
			dropoff_notes = form.cleaned_data['dropoff_notes']
			contact_number = form.cleaned_data['contact']
			delivery_type  = form.cleaned_data['delivery_type']
			delivery_date = form.cleaned_data['delivery_date']
			delivery_time = form.cleaned_data['delivery_time']
			flyer = form.cleaned_data['flyer']
			standard_fee = form.cleaned_data['standard_fee']
			priority_fee = form.cleaned_data['priority_fee']
			

			stop_spec_list = []
			stop_notes_list = []
			if stop1_address:
				stop_spec_list.append(stop1_spec)
				stop_notes_list.append(stop1_notes)
				if stop2_address:
					stop_spec_list.append(stop2_spec)
					stop_notes_list.append(stop2_notes)
					if stop3_address:
						stop_spec_list.append(stop3_spec)
						stop_notes_list.append(stop3_notes)
						if stop4_address:
							stop_spec_list.append(stop4_spec)
							stop_notes_list.append(stop4_notes)
							if stop5_address:
								stop_spec_list.append(stop5_spec)
								stop_notes_list.append(stop5_notes)
								if stop6_address:
									stop_spec_list.append(stop6_spec)
									stop_notes_list.append(stop6_notes)
				


			message = f'Hi there {name}, \n\nThank you for choosing CourtRun Legal Couriers to deliver your documents.'
			message += f'\n\nPickup Address: {pickup_address} \n\nPickup Address Specifications: {pickup_spec} \n\nPickup Notes: {pickup_notes}' 

			for i in range(stops):
				message += f'\n\n\nStop{i+1} Address: {stop_value[i]} \n\nStop{i+1} Address Specifications: {stop_spec_list[i]} \n\nStop{i+1} Notes: {stop_notes_list[i]}'

			message += f'\n\n\nDrop-off Address: {dropoff_address} \n\nDrop Address Specifications: {dropoff_spec} \n\nDrop-off Notes: {dropoff_notes}' 
			message += f'\n\n\nContact Number: {contact_number} \n\nDelivery Type: {delivery_type}'
			message += f'\nScheduled Delivery Date: {delivery_date} \nScheduled Delivery Time: {delivery_time}'
			message += f'\n\nProtective & Confidential Sleeve: {flyer}'
			message += f'\n\n\nThe email containing the payment link will provide a detailed breakdown of the total price.'
			message += f'\n\nWarm Regards,\nCourtRun Sales Team.'

			send_mail(subject=f'CourtRun Collect & Dropff Order Confirmation #{orderId}',
					message=message,
					from_email=settings.EMAIL_HOST_USER,
					recipient_list=[email],
					fail_silently=True
					)



			messageAdmin = f'Hi there {name}, \n\nThank you for choosing CourtRun Legal Couriers to deliver your documents.'
			messageAdmin += f'\n\nPickup Address: {pickup_address} \n\nPickup Address Specifications: {pickup_spec} \n\nPickup Notes: {pickup_notes}' 
			
			for i in range(stops):
				message += f'\n\n\nStop{i+1} Address: {stop_value[i]} \n\nStop{i+1} Address Specifications: {stop_spec_list[i]} \n\nStop{i+1} Notes: {stop_notes_list[i]}'			
			
			messageAdmin += f'\n\n\nDrop-off Address: {dropoff_address} \n\nDrop Address Specifications: {dropoff_spec} \n\nDrop-off Notes: {dropoff_notes}' 
			messageAdmin += f'\n\n\nContact Number: {contact_number} \n\nDelivery Type: {delivery_type}'
			messageAdmin += f'\nScheduled Delivery Date: {delivery_date} \nScheduled Delivery Time: {delivery_time}'
			messageAdmin += f'\n\nProtective & Confidential Sleeve: {flyer}'
			messageAdmin += f'\n\n\n\n\n==FEES FROM ORDER =='
			messageAdmin += f'\n\nStandard fee: {standard_fee}'
			messageAdmin += f'\nPriority fee: {priority_fee}'

			send_mail(subject=f'CourtRun Collect & Dropff Order Confirmation #{orderId}',
					message=messageAdmin,
					from_email=settings.EMAIL_HOST_USER,
					recipient_list=['courtrun.orders@zektechnologies.co.za'],
					fail_silently=True
					)

			return HttpResponseRedirect('confirmation/')
		else:
			print(form.errors.as_data())
			form = CollectionDropoffOrderForm
			if 'submitted' in request.GET:
				submitted = True

	form = CollectionDropoffOrderForm


	context = {
		"google_api_key": settings.GOOGLE_API_KEY,
		"lat_1": lat_1,
		"long_1": long_1,
		"name_1": name_addresses[0],
		"lat_2": lat_2,
		"long_2": long_2,
		"name_2": name_addresses[1],
		"lat_3": lat_3,
		"long_3": long_3,
		"lat_4": lat_4,
		"long_4": long_4,
		"lat_5": lat_5,
		"long_5": long_5,
		"lat_6": lat_6,
		"long_6": long_6,
		"lat_7": lat_7,
		"long_7": long_7,
		"lat_8": lat_8,
		"long_8": long_8,
		"origin": f'{lat_1}, {long_1}',
		"destination": f'{lat_2}, {long_2}',
		"directions": directions,
		"form": form,
		"submitted": submitted,
		'stop_fields': range(0, stops), 
		"stop_info": stop_info,
		"order_id": uuid.uuid4().hex[:12],
		"Priority_Fee": float(directions["priority_fee"]) + (15 * stops), 
		"Standard_Fee": float(directions["standard_fee"]) + (15 * stops), 
		

		} 
	return render(request, 'main/map.html', context)


def map_summon(request):

	lat_1 = request.GET.get("lat_1", None)
	long_1 = request.GET.get("long_1", None)
	lat_2 = request.GET.get("lat_2", None)
	long_2 = request.GET.get("long_2", None)
	lat_3 = request.GET.get("lat_3", None)
	long_3 = request.GET.get("long_3", None)

courtrun_legal_couriers/main/templates/main/confirmation.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}

<section class="py-5 mt-5">
    <div class="container py-4 py-xl-5">
        <div class="row mb-5">
            <div class="col-md-8 col-xl-6 text-center mx-auto">
                <h2 class="display-6 fw-bold mb-4"><span class="underline">Order Confirmation</span></h2>
            </div>
        </div>
        <div class="row gy-4 row-cols-1 row-cols-md-2 row-cols-lg-3" style="padding-top: 0px;">
           Your order has been confirmed. Please be advised that a confirmation email has been sent with the details of your order. You shall also recieve an email with a payment link.  
        </div>
    </div>

</section>

{% endblock %}

courtrun_legal_couriers/main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <section class="py-5 mt-5">
        <div class="container py-5">
            <div class="row">
                <div class="col-md-8 col-xl-6 text-center mx-auto">
                    <h2 class="display-6 fw-bold mb-4">Need&nbsp;<span class="underline">assistance</span>?</h2>
                    <p class="text-muted">Our team is always here to help. Send us a message and we'll get back to you shortly.</p>
                    <p class="text-muted">Optionally, you can give us a call at (+27) 69 199 0709</p>
                </div>
            </div>
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div>
                        <form id="ContactForm" class="p-3 p-xl-4" method="post" action="">
                            {% csrf_token %}
                            <div class="mb-3"><input class="shadow form-control" type="text" name="name" placeholder="Name"></div>
                            <div class="mb-3"><input class="shadow form-control" type="email" name="email" placeholder="Email"></div>
                            <div class="mb-3"><input class="shadow form-control" name="number" placeholder="Cellphone number"></div>
                            <div class="mb-3"><textarea class="shadow form-control"  name="message" rows="6" placeholder="Message"></textarea></div>
                            <div><button class="btn btn-primary shadow d-block w-100" type="submit">Send</button></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    {% endblock %}

courtrun_legal_couriers/main/templates/main/map-notice.html
{% extends 'main/base.html' %}
{% load static %}
{% load i18n %}



{% block content %}


<section class="py-5 mt-5">
  <div class="container py-5">
    <div class="row">
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            <h2 class="display-6 fw-bold mb-4"><span class="underline">Trip Details</span>.</h2>
        </div>
    </div>
    <div class="row d-flex justify-content-center">
        <div class="col-md-6">
            <div></div>
        </div>
    </div>
  </div>
</section>


<div class="map-container" style="margin-top: -100px; height: 75%; width: 100%;">
  <div id="map-route"></div>
</div>
<br>

<div class="container" style="margin-top: -150px;">
  <table>
    <tbody>

      <tr>
        <td>Duration:  </td>
        <td>{{directions.duration}}</td>      
      </tr>
      <tr>
        <td>Distance:  </td>
        <td>{{directions.distance}} </td>      
      </tr>
      <tr>
      <tr>
        <td>Directions:  </td>
        <td id="dir-toggle"><a href="javascript:void(0)" onclick="DirectionsToggle()"> CLICK HERE FOR DIRECTIONS</a></td>      
      </tr>

    </tbody>
  </table>

  <table id="dir-table" hidden>
    <thead>
      <tr>
        <th>Directions</th>
        <th>Distance</th>
        <th>Duration</th>
      </tr>
    </thead>
    <tbody>
      {% for leg in directions.route %}
          <tr>
          <td>Leg {{ forloop.counter }}</td>
          <td></td>
          <td></td>  
        </tr>
        {% for dist, dur, text in leg.steps %}
        <tr>
          <td>{{text|safe}}</td>
          <td>{{dist}}</td>
          <td>{{dur}}</td>   
        </tr>
        {% endfor %}
      {% endfor %}
    </tbody>
  </table>

</div>

<section class="py-5 mt-5">
  <div class="container py-5">
      <div class="row">
          <div class="col-md-8 col-xl-6 text-center mx-auto">
              <h2 class="display-6 fw-bold mb-4"><span class="underline">Order Request</span>.</h2>
              <p class="text-muted">Provide us with the details of your order request by completing the form below. Our team will promptly attend to your request.</p>
          </div>
      </div>
      <div class="row d-flex justify-content-center">
          <div class="col-md-6">
              <div></div>
          </div>
      </div>
  </div>

  <div class="container-fluid">
      <form id="OrderForm" method="POST" action="">
        {% csrf_token %}
          <div class="card shadow mb-3">
              <div class="card-body">
                  <div class="row">
                      <div class="col-sm-12 col-md-8 col-lg-8">
                          <div class="mb-3"><label class="form-label"><strong>Pickup Address Of Documents</strong></label>
                            <input class="form-control" type="text" id="id-google-address-1" value="{{name_1}}" name="pickup_address">
                          </div>
                          <div class="mb-3"><label class="form-label"><strong>Building/Complex, Office Number</strong></label>
                            {{ form.pickup_spec }}
                          </div>
                      </div>
                  </div>
                  <div class="mb-3"><label class="form-label"><strong>Pickup Address Additional Notes</strong></label>
                    {{ form.pickup_notes }}
                  </div>
                  <br><br><br>

                  {% for item1, item2, item3, item4, item5, item6 in stop_info %}
                    
                    <div class="row">
                      <div class="col-sm-12 col-md-8 col-lg-8">
                        
                          <div class="mb-3"><label class="form-label"><strong>Respondent {{item1}}</strong></label>
                            <input class="form-control" type="text" id="item2" value="{{item6}}" name="{{item3}}">
                          </div>
                          <div class="mb-3"><label class="form-label"><strong>Respondent {{item1}} Building/Complex, Office Number</strong></label>
                            <input class="form-control" type="text" id="{{item2}}" name="{{item4}}">
                          </div>
                      </div>
                    </div>
                    <div class="mb-3"><label class="form-label"><strong>Respondent {{item1}} Additional Notes</strong></label>
                      <textarea cols="40" rows="10" class="form-control" type="text" id="{{item5}}" name="{{item5}}" placeholder="Please provide us with the necessary contact information of the recipient, as well as any messages that should be conveyed to the recipient."></textarea>
                    </div>
                    <br><br><br>

                  {% endfor %}

                  <br><br><br>
                  <div class="row">
                      <div class="col-sm-12 col-md-8 col-lg-8">
                          <div class="mb-3"><label class="form-label" ><strong>DropOff Address For Handover Of Signed Documents</strong></label>
                            <input class="form-control" type="text" id="id-google-address-2" value="{{name_2}}" name="dropoff_address">
                          </div>
                          <div class="mb-3"><label class="form-label"><strong>Building/Complex, Office Number</strong></label>
                            {{ form.dropoff_spec }}
                          </div>
                      </div>
                  </div>
                  <div class="mb-3"><label class="form-label" ><strong>DropOff Address Additional Notes</strong></label>
                    {{ form.dropoff_notes }}
                  </div>
                  
                  <div class="col-md-8 col-xl-6 text-center mx-auto" style="margin-top: 100px;">
                    <h2 class="display-6 fw-bold mb-4"><span class="underline">Contact Details</span>.</h2>
                    <p class="text-muted" style="margin-top: -20px;">Provide us with your contact information to finalise your order.</p>
                </div>
                <div class="row">
                    <div class="col-sm-12 col-md-8 col-lg-8">
                        <div class="mb-3"><label class="form-label"><strong>Name of Individual/organisation requesting Delivery *</strong></label>
                          {{ form.name }}
                        </div>
                        <div class="mb-3"><label class="form-label"><strong>Email *</strong></label>
                            <p class="text-muted"><span style="color: rgb(255, 0, 0);">This email will receive payment link and delivery updates.</span></p>
                            {{ form.email }}
                        </div>
                        <div class="mb-3"><label class="form-label"><strong>Contact Number *</strong></label>
                            <p class="text-muted"><span style="color: rgb(255, 0, 0);">This contact number delivery updates.</span></p>
                            {{ form.contact }}
                        </div>
                    </div>
                </div>
                <br><br>

                <div class="mb-3"><label class="form-label"><strong>Delivery Date & Time</strong></label>
                  <p class="text-muted"><span style="color: rgb(255, 0, 0);">Select your preferred date of pickup below.</span></p>
                  {{ form.delivery_date }}
                  <br>
                  <p class="text-muted"><span style="color: rgb(255, 0, 0);">Select your preferred time of pickup below.</span></p>
                  {{ form.delivery_time }}

              </div>
              <br>
              <br>


              <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
                <thead>
                    <tr>
                        <th colspan="2" style="text-align: center;">DELIVERY TYPE FEES</th>
                    </tr>
                </thead>
                <tbody>
                      <td style="text-align: center;"><strong> STANDARD:  R{{Standard_Fee}}</strong></td>
                  </tr>
                  <tr>
                      <td style="text-align: center;"><strong>PRIORITY:  R{{Priority_Fee}}</strong></td>
                  </tr>
                  <tr><td>{{ form.delivery_type }}</td></tr>  
          
                </tbody>
            </table>

            <br><br>
            <div class="col"><label class="form-label" ><strong>Protective & Confidential Flyer (R15.00/bag)</strong></label>
              <p class="text-muted"><span style="color: rgb(255, 0, 0);">We already provide a single courier bag to fully protect your documents and keep them as confidential as possible. Should you require more please select how many you would need.</span></p>
              {{ form.flyer }}
            </div>


          </div>
      </div>
      <input type="hidden" name="standard_fee" value="{{Standard_Fee}}">
      <input type="hidden" name="priority_fee" value="{{Priority_Fee}}">
      <input type="hidden" name="order_id" value="{{order_id}}">
      <input type="hidden" name="pickup_coordinates" value="{{lat_1}}, {{long_1}}">
      <input type="hidden" name="stop1_coordinates" value="{{lat_3}}, {{long_3}}">
      <input type="hidden" name="stop2_coordinates" value="{{lat_4}}, {{long_4}}">
      <input type="hidden" name="stop3_coordinates" value="{{lat_5}}, {{long_5}}">
      <input type="hidden" name="stop4_coordinates" value="{{lat_6}}, {{long_6}}">
      <input type="hidden" name="stop5_coordinates" value="{{lat_7}}, {{long_7}}">
      <input type="hidden" name="stop6_coordinates" value="{{lat_8}}, {{long_8}}">
      <input type="hidden" name="dropoff_coordinates" value="{{lat_2}}, {{long_2}}">
          

          <div class="text-end mb-3">
            <input type="submit" value="Submit" class="btn btn-secondary">
          </div>
      </form>
  </div>
</section>

{% endblock %}

{% block extend_footer %}

<script type="text/javascript">

  var google_api_key = "{{google_api_key|safe}}";
  var lat_1 = {{lat_1|safe}};
  var long_1 = {{long_1|safe}};
  var lat_2 = {{lat_2|safe}};
  var long_2 = {{long_2|safe}};
  var lat_3 = {{lat_3|safe}};
  var long_3 = {{long_3|safe}};
  var lat_4 = {{lat_4|safe}};
  var long_4 = {{long_4|safe}};
  var lat_5 = {{lat_5|safe}};
  var long_5 = {{long_5|safe}};
  var lat_6 = {{lat_6|safe}};
  var long_6 = {{long_6|safe}};
  var lat_7 = {{lat_7|safe}};
  var long_7 = {{long_7|safe}};
  var lat_8 = {{lat_8|safe}};
  var long_8 = {{long_8|safe}};
  var origin = "{{origin|safe}}";
  var destination = "{{destination|safe}}";
  var directions = {{directions|safe}};

</script>
<script src="{% static 'google_maps.js' %}"></script>



{% endblock %}

courtrun_legal_couriers/main/templates/main/page-not-found.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
    <section class="py-5 mt-5">
        <div class="container">
            <div class="row row-cols-1 d-flex justify-content-center align-items-center">
                <div class="col-md-10 text-center"><img class="img-fluid w-100" src="{% static 'courtrun_legal_couriers/media/404.svg' %}"></div>
                <div class="col text-center">
                    <h2 class="display-3 fw-bold mb-4">Page Not Found</h2>
                    <p class="fs-4 text-muted">Oops! Looks like we got nothing here :(</p>
                </div>
            </div>
        </div>
    </section>
 {% endblock %}

 

courtrun_legal_couriers/main/templates/main/selection.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}

<section class="py-5 mt-5">
  <div class="container py-5">
      <div class="row">
          <div class="col-md-8 col-xl-6 text-center mx-auto">
              <h2 class="display-6 fw-bold mb-4"><span class="underline">Order Request</span>.</h2>
              <p class="text-muted">Kindly specify the service you would like to complete with us.</p>
          </div>
      </div>

  </div>
  <div class="container" >
        <div class="col-md-8 col-xl-6 text-center mx-auto">
            <div>
                <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route_file' %}">FILE</a>
            </div>
            <br><br>
            <div>
                <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route_serve' %}">SERVE</a>
            </div>
            <br><br>


            <div>
                <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route_notice' %}">NOTICE</a>
            </div>
            <br><br>

            <div>
              <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route_summon' %}">SUMMON</a>
          </div>

            <br><br>
            <div>
                <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route' %}">COLLECTION & DROPOFF</a>
            </div>
            <br><br>
            <div>
                <a class="btn btn-primary shadow btn-lg" role="button" href="{% url 'main:route_correspondence' %}">OTHER CORRESPONDENCE</a>
            </div>
        </div> 
  </div>


</section>

{% endblock %}

{% block extend_footer %}

{% endblock %}